<div style="float: left; width:300px">
	<h2>Logo Options</h2>
    <?php echo $this->form; ?>
</div>

<div style="float: left; width:640px">
	<h2>Preview</h2>
	<div id="preview"></div>
	<div style="font-size:12px; padding-top: 20px; width: 600px">
		<b>Image URL: </b><br /><a target="_blank" id="imgUrl" href=""></a>
	</div>
	<br /><br />
	<h2>Usage Notes</h2>
	<ol>
		<li><b>Branding</b><br />
		No matter the image created with this tool, it is still important that usage abides by the guidelines set
		forth by the <a href="http://ncsu.edu/brand">NC State Branding Guidelines</a>.
		</li>
		
		<li><b>Color Selection for Website Headers</b><br />
		If generating a logo for a header image on a website, it must consist of only the primary colors: Red, Black 
		and White.  All other color combinations should not be used for the main headers of a website.
		</li>
		
		<li><b>Accessible Color Combinations</b><br />
		While color combinations for font vs. background colors can be customized, it is important that the combinations
		you use abide by the WCAG 2 Level AA guidelines.  To better help you pick these colors, refer to the
		<a href="http://accessibility.oit.ncsu.edu/tools/color-contrast/accessible-color-palette.php?&primary=CC0000,000000,FFFFFF&secondary=383838,666666,CCCCCC,E1E1E1,5C5541,666633,556677,A20000&tertiary=A79574,C5BD9D,E5E1D0,778855,99AA77,CCDDAA,67849C,CC9900&level=AA&ncsu=1">
		NC State University Color Palette Accessibility Checker</a>.
		</li>
		
		<li><b>Saving the image</b><br />
		You can save this image to your local webspace by right-clicking on the image and select "Save As...".  This is
		the preferred method of usage.
		</li>
		<li><b>Direct Linking</b><br />
		You can directly link to this service by using this image URL.  Set
		this as the <b>src</b> of your <b>img</b> tag.
		</li>
	</ol>
</div>

<textarea id="initialColors"><?php echo $this->colors; ?></textarea>
<input type="hidden" id="apiUrl" value="<?php echo $this->apiUrl; ?>" />