<div style="float: left; width:200px">
	<h2>Logo Options</h2>
    <?php echo $this->form; ?>
</div>

<div style="float: left; width:740px">
	<h2>Preview</h2>
	<div id="preview"></div>
	<div style="font-size:12px; padding-top: 20px; width: 600px">
		<b>Image URL: </b><br /><a target="_blank" id="imgUrl" href=""></a>
	</div>
	<br /><br />
	<h2>Usage Notes</h2>
	<ol>
		<li><b>Branding</b><br />
		No matter the image created with this tool, it is still important that usage abides by the guidelines set
		forth by the <a href="http://ncsu.edu/brand">NC State Branding Guidelines</a>.
		</li>
		<li><b>Word Separation</b><br />
		By default, the <b>boldText</b> and <b>normalText</b> fields will not be spaced out.  To make the illusion of
		two separate words, you should be a space at the end of the <b>boldText</b> string or the beginning of the <b>normalText</b>
		string.
		</li>
		<li><b>Saving the image</b><br />
		You can save this image to your local webspace by right-clicking on the image and select "Save As...".  This is
		the preferred method of usage.
		</li>
		<li><b>Direct Linking</b><br />
		You can directly link to this service by using this image URL.  Set
		this as the <b>src</b> of your <b>img</b> tag.
		</li>
	</ol>
</div>

<textarea id="initialColors"><?php echo $this->colors; ?></textarea>
<input type="hidden" id="apiUrl" value="<?php echo $this->apiUrl; ?>" />